# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScoutCNF.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from ScoutCNF_Widgets import keyPressQLineEdit,keyPressQLineEdit2,keyPressQLineEdit3

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 331)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.MainWindowTab = QtWidgets.QTabWidget(self.centralwidget)
        self.MainWindowTab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.MainWindowTab.setElideMode(QtCore.Qt.ElideNone)
        self.MainWindowTab.setObjectName("MainWindowTab")
        self.foodSearchTab = QtWidgets.QWidget()
        self.foodSearchTab.setObjectName("foodSearchTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.foodSearchTab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchLayout = QtWidgets.QVBoxLayout()
        self.searchLayout.setSpacing(3)
        self.searchLayout.setObjectName("searchLayout")
        self.searchEntryLabel = QtWidgets.QLabel(self.foodSearchTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.searchEntryLabel.setFont(font)
        self.searchEntryLabel.setTextFormat(QtCore.Qt.AutoText)
        self.searchEntryLabel.setObjectName("searchEntryLabel")
        self.searchLayout.addWidget(self.searchEntryLabel)
#        self.searchEntryLine = QtWidgets.QLineEdit(self.foodSearchTab)
        self.searchEntryLine = keyPressQLineEdit(self.foodSearchTab)
        self.searchEntryLine.setObjectName("searchEntryLine")
        self.searchLayout.addWidget(self.searchEntryLine)
        self.foodCategoryList = QtWidgets.QListWidget(self.foodSearchTab)
        self.foodCategoryList.setObjectName("foodCategoryList")
        self.searchLayout.addWidget(self.foodCategoryList)
        self.horizontalLayout.addLayout(self.searchLayout)
        self.searchResultLayout = QtWidgets.QVBoxLayout()
        self.searchResultLayout.setSpacing(3)
        self.searchResultLayout.setObjectName("searchResultLayout")
        self.searchResultLabel = QtWidgets.QLabel(self.foodSearchTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.searchResultLabel.setFont(font)
        self.searchResultLabel.setTextFormat(QtCore.Qt.AutoText)
        self.searchResultLabel.setObjectName("searchResultLabel")
        self.searchResultLayout.addWidget(self.searchResultLabel)
        self.specFoodList = QtWidgets.QListWidget(self.foodSearchTab)
        self.specFoodList.setObjectName("specFoodList")
        self.searchResultLayout.addWidget(self.specFoodList)
        self.horizontalLayout.addLayout(self.searchResultLayout)
        self.foodPortionLayout = QtWidgets.QVBoxLayout()
        self.foodPortionLayout.setSpacing(3)
        self.foodPortionLayout.setObjectName("foodPortionLayout")
        self.foodPortionLabel = QtWidgets.QLabel(self.foodSearchTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.foodPortionLabel.setFont(font)
        self.foodPortionLabel.setTextFormat(QtCore.Qt.AutoText)
        self.foodPortionLabel.setObjectName("foodPortionLabel")
        self.foodPortionLayout.addWidget(self.foodPortionLabel)
        self.foodPortionList = QtWidgets.QListWidget(self.foodSearchTab)
        self.foodPortionList.setObjectName("foodPortionList")
        self.foodPortionLayout.addWidget(self.foodPortionList)
        self.horizontalLayout.addLayout(self.foodPortionLayout)
        self.portionLayout = QtWidgets.QVBoxLayout()
        self.portionLayout.setSpacing(3)
        self.portionLayout.setObjectName("portionLayout")
        self.portionLabel = QtWidgets.QLabel(self.foodSearchTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.portionLabel.setFont(font)
        self.portionLabel.setTextFormat(QtCore.Qt.AutoText)
        self.portionLabel.setObjectName("portionLabel")
        self.portionLayout.addWidget(self.portionLabel)
        self.portionEntryLine = QtWidgets.QLineEdit(self.foodSearchTab)
        self.portionEntryLine.setObjectName("portionEntryLine")
        self.portionLayout.addWidget(self.portionEntryLine)
        self.addSelectionButton = QtWidgets.QPushButton(self.foodSearchTab)
        self.addSelectionButton.setObjectName("addSelectionButton")
        self.portionLayout.addWidget(self.addSelectionButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.portionLayout.addItem(spacerItem)
        self.saveSelectionButton = QtWidgets.QPushButton(self.foodSearchTab)
        self.saveSelectionButton.setObjectName("saveSelectionButton")
        self.portionLayout.addWidget(self.saveSelectionButton)
        self.horizontalLayout.addLayout(self.portionLayout)
        self.selectedFoodLayout = QtWidgets.QVBoxLayout()
        self.selectedFoodLayout.setSpacing(3)
        self.selectedFoodLayout.setObjectName("selectedFoodLayout")
        self.selectedListLabel = QtWidgets.QLabel(self.foodSearchTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectedListLabel.setFont(font)
        self.selectedListLabel.setTextFormat(QtCore.Qt.AutoText)
        self.selectedListLabel.setObjectName("selectedListLabel")
        self.selectedFoodLayout.addWidget(self.selectedListLabel)
        self.selectedFoodList = QtWidgets.QListWidget(self.foodSearchTab)
        self.selectedFoodList.setObjectName("selectedFoodList")
        self.selectedFoodLayout.addWidget(self.selectedFoodList)
        self.outputDirLabel = QtWidgets.QLabel(self.foodSearchTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.outputDirLabel.setFont(font)
        self.outputDirLabel.setTextFormat(QtCore.Qt.AutoText)
        self.outputDirLabel.setObjectName("outputDirLabel")
        self.selectedFoodLayout.addWidget(self.outputDirLabel)
#        self.outputDirEntryLine = QtWidgets.QLineEdit(self.foodSearchTab)
        self.outputDirEntryLine = keyPressQLineEdit2(self.foodSearchTab)
        self.outputDirEntryLine.setObjectName("outputDirEntryLine")
        self.selectedFoodLayout.addWidget(self.outputDirEntryLine)
        self.horizontalLayout.addLayout(self.selectedFoodLayout)
        self.MainWindowTab.addTab(self.foodSearchTab, "")
        self.analysisTab = QtWidgets.QWidget()
        self.analysisTab.setObjectName("analysisTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.analysisTab)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RDI_Layout = QtWidgets.QVBoxLayout()
        self.RDI_Layout.setSpacing(3)
        self.RDI_Layout.setObjectName("RDI_Layout")
        self.RDI_DirLabel = QtWidgets.QLabel(self.analysisTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.RDI_DirLabel.setFont(font)
        self.RDI_DirLabel.setTextFormat(QtCore.Qt.AutoText)
        self.RDI_DirLabel.setObjectName("RDI_DirLabel")
        self.RDI_Layout.addWidget(self.RDI_DirLabel)
#        self.RDI_DirLineEntry = QtWidgets.QLineEdit(self.analysisTab)
        self.RDI_DirLineEntry = keyPressQLineEdit3(self.analysisTab)
        self.RDI_DirLineEntry.setObjectName("RDI_DirLineEntry")
        self.RDI_Layout.addWidget(self.RDI_DirLineEntry)
        self.RDI_SummaryList = QtWidgets.QListWidget(self.analysisTab)
        self.RDI_SummaryList.setObjectName("RDI_SummaryList")
        self.RDI_Layout.addWidget(self.RDI_SummaryList)
        self.horizontalLayout_3.addLayout(self.RDI_Layout)
        self.subjectLayout = QtWidgets.QVBoxLayout()
        self.subjectLayout.setSpacing(3)
        self.subjectLayout.setObjectName("subjectLayout")
        self.subjectDirLabel = QtWidgets.QLabel(self.analysisTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.subjectDirLabel.setFont(font)
        self.subjectDirLabel.setTextFormat(QtCore.Qt.AutoText)
        self.subjectDirLabel.setObjectName("subjectDirLabel")
        self.subjectLayout.addWidget(self.subjectDirLabel)
#        self.subjectDirLineEntry = QtWidgets.QLineEdit(self.analysisTab)
        self.subjectDirLineEntry = keyPressQLineEdit3(self.analysisTab)
        self.subjectDirLineEntry.setObjectName("subjectDirLineEntry")
        self.subjectLayout.addWidget(self.subjectDirLineEntry)
        self.subjectSummaryList = QtWidgets.QListWidget(self.analysisTab)
        self.subjectSummaryList.setObjectName("subjectSummaryList")
        self.subjectLayout.addWidget(self.subjectSummaryList)
        self.horizontalLayout_3.addLayout(self.subjectLayout)
        self.analysisOutLayout = QtWidgets.QVBoxLayout()
        self.analysisOutLayout.setObjectName("analysisOutLayout")
        self.numDaysLabel = QtWidgets.QLabel(self.analysisTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.numDaysLabel.setFont(font)
        self.numDaysLabel.setTextFormat(QtCore.Qt.AutoText)
        self.numDaysLabel.setObjectName("numDaysLabel")
        self.analysisOutLayout.addWidget(self.numDaysLabel)
        self.numDaysLineEntry = QtWidgets.QLineEdit(self.analysisTab)
        self.numDaysLineEntry.setObjectName("numDaysLineEntry")
        self.analysisOutLayout.addWidget(self.numDaysLineEntry)
        self.outputDirLabel_2 = QtWidgets.QLabel(self.analysisTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.outputDirLabel_2.setFont(font)
        self.outputDirLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.outputDirLabel_2.setObjectName("outputDirLabel_2")
        self.analysisOutLayout.addWidget(self.outputDirLabel_2)
#        self.outputDirEntryLine_2 = QtWidgets.QLineEdit(self.analysisTab)
        self.outputDirEntryLine_2 = keyPressQLineEdit2(self.analysisTab)
        self.outputDirEntryLine_2.setObjectName("outputDirEntryLine_2")
        self.analysisOutLayout.addWidget(self.outputDirEntryLine_2)
        self.compareButton = QtWidgets.QPushButton(self.analysisTab)
        self.compareButton.setObjectName("compareButton")
        self.analysisOutLayout.addWidget(self.compareButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.analysisOutLayout.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.analysisOutLayout)
        spacerItem2 = QtWidgets.QSpacerItem(231, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.MainWindowTab.addTab(self.analysisTab, "")
        self.horizontalLayout_2.addWidget(self.MainWindowTab)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.MainWindowTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchEntryLabel.setText(_translate("MainWindow", "Search Input"))
        self.searchResultLabel.setText(_translate("MainWindow", "Search Result"))
        self.foodPortionLabel.setText(_translate("MainWindow", "Measurement Unit"))
        self.portionLabel.setText(_translate("MainWindow", "Portion"))
        self.addSelectionButton.setText(_translate("MainWindow", "Add"))
        self.saveSelectionButton.setText(_translate("MainWindow", "Save"))
        self.selectedListLabel.setText(_translate("MainWindow", "Selected Foods"))
        self.outputDirLabel.setText(_translate("MainWindow", "Output File Location"))
        self.MainWindowTab.setTabText(self.MainWindowTab.indexOf(self.foodSearchTab), _translate("MainWindow", "Food Search"))
        self.RDI_DirLabel.setText(_translate("MainWindow", "RDIs Folder"))
        self.subjectDirLabel.setText(_translate("MainWindow", "Subject Folder"))
        self.numDaysLabel.setText(_translate("MainWindow", "Number of Days"))
        self.outputDirLabel_2.setText(_translate("MainWindow", "Output File Location"))
        self.compareButton.setText(_translate("MainWindow", "Compare"))
        self.MainWindowTab.setTabText(self.MainWindowTab.indexOf(self.analysisTab), _translate("MainWindow", "Analysis"))

